// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XMLWebApiCore.Models.DBClasses;

#nullable disable

namespace XMLWebApiCore.Migrations
{
    [DbContext(typeof(FileServiceContext))]
    [Migration("20220531090928_xmlFile")]
    partial class xmlFile
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("XMLWebApiCore.Models.DBClasses.Drawing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("MaxX")
                        .HasColumnType("float");

                    b.Property<double>("MaxY")
                        .HasColumnType("float");

                    b.Property<double>("MinX")
                        .HasColumnType("float");

                    b.Property<double>("MinY")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drawings");
                });

            modelBuilder.Entity("XMLWebApiCore.Models.DBClasses.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ComponentClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DrawingId")
                        .HasColumnType("int");

                    b.Property<double>("LocationX")
                        .HasColumnType("float");

                    b.Property<double>("LocationY")
                        .HasColumnType("float");

                    b.Property<double>("MaxX")
                        .HasColumnType("float");

                    b.Property<double>("MaxY")
                        .HasColumnType("float");

                    b.Property<double>("MinX")
                        .HasColumnType("float");

                    b.Property<double>("MinY")
                        .HasColumnType("float");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrawingId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("XMLWebApiCore.Models.DBClasses.InstrumentComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ComponentClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DrawingId")
                        .HasColumnType("int");

                    b.Property<double>("LocationX")
                        .HasColumnType("float");

                    b.Property<double>("LocationY")
                        .HasColumnType("float");

                    b.Property<double>("MaxX")
                        .HasColumnType("float");

                    b.Property<double>("MaxY")
                        .HasColumnType("float");

                    b.Property<double>("MinX")
                        .HasColumnType("float");

                    b.Property<double>("MinY")
                        .HasColumnType("float");

                    b.Property<string>("PersistentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrawingId");

                    b.ToTable("InstrumentComponents");
                });

            modelBuilder.Entity("XMLWebApiCore.Models.DBClasses.Nozzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ComponentClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<double>("LocationX")
                        .HasColumnType("float");

                    b.Property<double>("LocationY")
                        .HasColumnType("float");

                    b.Property<double>("MaxX")
                        .HasColumnType("float");

                    b.Property<double>("MaxY")
                        .HasColumnType("float");

                    b.Property<double>("MinX")
                        .HasColumnType("float");

                    b.Property<double>("MinY")
                        .HasColumnType("float");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("Nozzles");
                });

            modelBuilder.Entity("XMLWebApiCore.Models.DBClasses.PipeConnectorSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ComponentClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrossPageDrawingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrossPageLinkLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DrawingId")
                        .HasColumnType("int");

                    b.Property<double>("LocationX")
                        .HasColumnType("float");

                    b.Property<double>("LocationY")
                        .HasColumnType("float");

                    b.Property<double>("MaxX")
                        .HasColumnType("float");

                    b.Property<double>("MaxY")
                        .HasColumnType("float");

                    b.Property<double>("MinX")
                        .HasColumnType("float");

                    b.Property<double>("MinY")
                        .HasColumnType("float");

                    b.Property<string>("PersistentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrawingId");

                    b.ToTable("PipeConnectorSymbols");
                });

            modelBuilder.Entity("XMLWebApiCore.Models.DBClasses.Equipment", b =>
                {
                    b.HasOne("XMLWebApiCore.Models.DBClasses.Drawing", null)
                        .WithMany("Equipments")
                        .HasForeignKey("DrawingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XMLWebApiCore.Models.DBClasses.InstrumentComponent", b =>
                {
                    b.HasOne("XMLWebApiCore.Models.DBClasses.Drawing", null)
                        .WithMany("InstrumentComponents")
                        .HasForeignKey("DrawingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XMLWebApiCore.Models.DBClasses.Nozzle", b =>
                {
                    b.HasOne("XMLWebApiCore.Models.DBClasses.Equipment", null)
                        .WithMany("Nozzles")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XMLWebApiCore.Models.DBClasses.PipeConnectorSymbol", b =>
                {
                    b.HasOne("XMLWebApiCore.Models.DBClasses.Drawing", null)
                        .WithMany("PipeConnectorSymbols")
                        .HasForeignKey("DrawingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XMLWebApiCore.Models.DBClasses.Drawing", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("InstrumentComponents");

                    b.Navigation("PipeConnectorSymbols");
                });

            modelBuilder.Entity("XMLWebApiCore.Models.DBClasses.Equipment", b =>
                {
                    b.Navigation("Nozzles");
                });
#pragma warning restore 612, 618
        }
    }
}
